name: restaurant_pos_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  gap: ^3.0.1
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  calendar_date_picker2: ^0.5.2
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.1
  flutter_gb_pos_nfc: ^0.0.2
  flutter_nfc_kit: ^3.3.1
  nfc_manager:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
 
    

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
